### ISSUE TITLE
Blogs categories not being saved.

### ISSUE THREAD

**Issue by Athuli7** [totaljs/blogengine#2]
When you update the categories in the settings page, it won't be updated.

**Comment by petersirka** [comment]
Hi @Athuli7, pleasy try to use a new beta version of __BlogEngine__. <https://github.com/totaljs/blogengine/tree/v2.0.0>

**Comment by dlplenin** [comment]
@Athuli7  I had the same behave, it was when you don't put a correct value to URL address", version 1.0.0 dont show an error but it block you save the data.

@petersirka yes, with version 2.0.0 it is working!
