### ISSUE TITLE
Blog throw error when update the category

### ISSUE THREAD

**Issue by flashvnn** [totaljs/blogengine#4]
Hi petersirka,
The blogengine is great, it very lightweight and easy to deploy. But i have an issue, when i change (update) exist category name it still keep old name and make blog throw error page not found.
Can you update code to allow i can change the category name?
Thank

**Comment by petersirka** [comment]
Hi @flashvnn,
than you. Now, I don't have solution for it... It's a bit complicated because I don't know what I have do with non-existing categories in blog posts 👍
