### ISSUE TITLE
Test Blog Engine

### ISSUE THREAD

**Issue by NMathar** [totaljs/blogengine#5]
Hi Peter,

i playe around with your blog engine on superadmin and its is a realy nice blog but i get some errors.

I get this error in my browser console on edit a blog entry:

`VM7811:1 Uncaught ReferenceError: index is not defined
    at <anonymous>:1:1460
    at manager.js:5
    at $MIDDLEWARE (manager.js:5)
    at Object.r.success (manager.js:5)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)`

code
`
response.draft_old=response.draft;SET('blogs.form', $.extend({ $index:index,tab:'edit'},response),true);SET('blogs.response',null);
`

and on first try i get a 500 response for preview blog body. but thats now magicaly done 😄 

and one little change for template (themes/default/views/blogs/partial-blogs.html) 

````html
@{if m.picture }<a href="@{sitemap_url('detail', m.category_linker, m.linker)}" class="picture"><img src="/download/@{m.picture}" class="img-responsive img-rounded" /></a>@{fi}
````

**Comment by petersirka** [comment]
Hi @NMonst4,
do you have latest version from GitHub or a version installed via SuperAdmin?

PS: thank you I have updated that view.

**Comment by NMathar** [comment]
Hi @petersirka 

yes i have tested all versions. From superadmin from github and from my.totaljs.com. I still get this error.

**Comment by NMonst4** [comment]
And same little fix for themes/default/views/blogs/detail.html

````html
@{if m.picture }<div><img src="/download/@{model.picture}" class="img-responsive img-rounded" alt="@{model.name}" /></div>{fi}
````

**Comment by NMathar** [comment]
There is no problem on my local dev instance only on superadmin v5.0. 

Is that reproduceable for you?

**Comment by NMathar** [comment]
Hi @petersirka 

now with superadmin v7 and default superadmin blogengine package it works like a charm. I dont know why :/

**Comment by petersirka** [comment]
It's because of Amazon CDN, it's not fast for refreshing :-D
